header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - "**/*.go"
    - "**/*.s"

  paths-ignore:
    - "parser/function.peg.go"
    - "examples/custom-function"

  comment: on-failure
